package sfgamedataeditor.dataextraction;

public enum DTOOffsetTypes {
    SKILL_PARAMETERS,
    SPELL_PARAMETERS,
    CREATURE_PARAMETERS,
    CREATURE_COMMON_PARAMETERS,
    CREATURE_SPELLS,
    CREATURE_EQUIPMENT,
    CREATURE_CORPSE_LOOT,
    CREATURE_BUILDINGS,
    CREATURE_RESOURCES,
    CREATURE_SKILLS,
    ITEM_EFFECTS,
    ITEM_SPELL_EFFECTS,
    ITEM_REQUIREMENTS,
    WEAPON_PARAMETERS,
    ARMOR_PARAMETERS,
    MERCHANT_INVENTORY,
    MERCHANT_INVENTORY_ITEMS,
    BUILDINGS,
    ITEM_PRICES
}
