package views;

import javax.swing.*;
import java.awt.*;

public class SkillRequrementView {
    private JPanel mainPanel;
    private JTextField strengthTextField;
    private JLabel stregthLabel;
    private JTextField staminaField;
    private JLabel staminaLabel;
    private JTextField agilityField;
    private JLabel agilityLabel;
    private JLabel dexterityLabel;
    private JTextField dexterityField;
    private JLabel intelligenceLabel;
    private JTextField intelligenceField;
    private JLabel wisdomLabel;
    private JTextField wisdomField;
    private JLabel charismaLabel;
    private JTextField charismaField;
    private JPanel layoutPanel;
    private JLabel skillNameLabel;
    private JSeparator skillNameSeparator;

    public SkillRequrementView() {
        generateUI();
    }

    private void generateUI() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        layoutPanel = new JPanel();
        layoutPanel.setLayout(new GridBagLayout());
        layoutPanel.setAutoscrolls(false);
        layoutPanel.setMinimumSize(new Dimension(440, 38));
        layoutPanel.setOpaque(true);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(layoutPanel, gbc);
        stregthLabel = new JLabel();
        stregthLabel.setText("Strength:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 20;
        layoutPanel.add(stregthLabel, gbc);
        strengthTextField = new JTextField();
        strengthTextField.setOpaque(true);
        strengthTextField.setPreferredSize(new Dimension(35, 23));
        strengthTextField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        layoutPanel.add(strengthTextField, gbc);
        staminaLabel = new JLabel();
        staminaLabel.setText("Stamina:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 20;
        layoutPanel.add(staminaLabel, gbc);
        staminaField = new JTextField();
        staminaField.setPreferredSize(new Dimension(35, 23));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        layoutPanel.add(staminaField, gbc);
        agilityLabel = new JLabel();
        agilityLabel.setText("Agility:");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 20;
        layoutPanel.add(agilityLabel, gbc);
        agilityField = new JTextField();
        agilityField.setPreferredSize(new Dimension(35, 23));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        layoutPanel.add(agilityField, gbc);
        dexterityLabel = new JLabel();
        dexterityLabel.setText("Dexterity:");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 20;
        layoutPanel.add(dexterityLabel, gbc);
        dexterityField = new JTextField();
        dexterityField.setPreferredSize(new Dimension(35, 23));
        dexterityField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        layoutPanel.add(dexterityField, gbc);
        intelligenceLabel = new JLabel();
        intelligenceLabel.setText("Intelligence:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 20;
        layoutPanel.add(intelligenceLabel, gbc);
        intelligenceField = new JTextField();
        intelligenceField.setPreferredSize(new Dimension(35, 23));
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 3;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        layoutPanel.add(intelligenceField, gbc);
        wisdomLabel = new JLabel();
        wisdomLabel.setText("Wisdom:");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 20;
        layoutPanel.add(wisdomLabel, gbc);
        wisdomField = new JTextField();
        wisdomField.setPreferredSize(new Dimension(35, 23));
        wisdomField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 3;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        layoutPanel.add(wisdomField, gbc);
        charismaLabel = new JLabel();
        charismaLabel.setText("Charisma:");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 20;
        layoutPanel.add(charismaLabel, gbc);
        charismaField = new JTextField();
        charismaField.setPreferredSize(new Dimension(35, 23));
        charismaField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        layoutPanel.add(charismaField, gbc);
        skillNameLabel = new JLabel();
        skillNameLabel.setText("SkillName:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        layoutPanel.add(skillNameLabel, gbc);
        skillNameSeparator = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 0, 10, 0);
        layoutPanel.add(skillNameSeparator, gbc);
        stregthLabel.setLabelFor(strengthTextField);
    }

    public void setSkillName(String skillName) {
        skillNameLabel.setText(skillName);
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

}
